version: '3'
services:
  backend:
    build:
      context: ./Backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGODB_URI=mongodb+srv://kamran:5XvG4bRRW6BUbrmg@cluster0.njzbkkr.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      - JWT_SECRET=your_jwt_secret_key_here
      - JWT_EXPIRE=30d
      - JWT_COOKIE_EXPIRE=30
      - MAPBOX_ACCESS_TOKEN=pk.eyJ1Ijoia2FtcmFuLTAwMyIsImEiOiJjbTQzM3NoOWowNzViMnFzNHBwb2wwZ2k0In0.DHxC51GY9USAaRFeqH7awQ
    networks:
      - app-network
  frontend:
    build:
      context: ./Frontend/display
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    networks:
      - app-network

networks:
  app-network:
    driver: bridge